[package]
name = "mapping-tools-web"
version = "0.1.0"
authors = ["Michael Zhang <mail@mzhang.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17.4"
mapping-tools = { path = ".." }
wasm-bindgen = "0.2.70"
libosu = { git = "https://github.com/iptq/libosu" }
