name: Build and Deploy

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cache cargo plugins
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-bins

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo install wasm-pack

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        working-directory: mapping-tools-web
        run: |
          npm install
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: mapping-tools-web/dist
